"""
Helper classes for creating maps in any Source Engine game that uses cstrike.fgd.
This file was auto-generated by import_fgd.py on 2020-01-15 18:10:33.149075.
"""

from vmflib2.vmf import *


class EnvDetailController(Entity):
    """
    Auto-generated from cstrike.fgd, line 118.
    An entity that lets you control the fade distances for detail props.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0", fademindist: float=400, fademaxdist: float=1200):
        Entity.__init__(self, "env_detail_controller", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Start Fade Dist/Pixels : Distance at which the prop starts to fade.
        self.fademindist: float = fademindist
        # End Fade Dist/Pixels : Maximum distance at which the prop is visible.
        self.fademaxdist: float = fademaxdist

        self.auto_properties.extend(["origin", "angles", "fademindist", "fademaxdist"])


class FilterActivatorTeam(Entity):
    """
    Auto-generated from cstrike.fgd, line 42.
    A filter that filters by the team of the activator.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", Negated="Allow entities that match criteria", filterteam=2):
        Entity.__init__(self, "filter_activator_team", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Filter mode : If set to Allow, only entities who match the criteria will pass the filter. 
        self.Negated = Negated

        # Filter Team Number : The team number to filter by.  If the filter mode is Allow, only entities whose 
        self.filterteam = filterteam

        self.auto_properties.extend(["origin", "targetname", "Negated", "filterteam"])


class FuncBombTarget(Entity):
    """
    Auto-generated from cstrike.fgd, line 195.
    Bomb Target. The terrorists can place C4 explosives while standing in this zone.\n\nWhen the bomb is planted and explodes inside this area, the BombExplode outputs are fired. The game handles all of the bomb planting and scoring logic – the BombExplode outputs are provided to add visual and damage effects.
    """
    def __init__(self, vmf_map: "ValveMap", targetname: str="", parentname: str="", heistbomb=0, bomb_mount_target: str=""):
        Entity.__init__(self, "func_bomb_target", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname: str = parentname

        # Heist Mode bomb target : This is a Bomb Target designed for the Heist game mode.
        self.heistbomb = heistbomb
        # Bomb Mount Target : 
        self.bomb_mount_target: str = bomb_mount_target

        self.auto_properties.extend(["targetname", "parentname", "heistbomb", "bomb_mount_target"])


class FuncBuyzone(Entity):
    """
    Auto-generated from cstrike.fgd, line 188.
    Buy Zone. Players can buy equipment while standing in this zone, if the zone matches their current team.\n\nA single Buy Zone entity must be either terrorist or counter-terrorist, it cannot be both. Should have the toolstrigger material applied to all sides
    """
    def __init__(self, vmf_map: "ValveMap", targetname: str="", TeamNum=0):
        Entity.__init__(self, "func_buyzone", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Team Number (int) : 
        self.TeamNum = TeamNum


        self.auto_properties.extend(["targetname", "TeamNum"])


class FuncHostageRescue(Entity):
    """
    Auto-generated from cstrike.fgd, line 213.
    Hostage Rescue Zone. When a hostage is led into this zone, it is marked as rescued.
    """
    def __init__(self, vmf_map: "ValveMap", targetname: str=""):
        Entity.__init__(self, "func_hostage_rescue", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname


        self.auto_properties.extend(["targetname"])


class FuncLadder(Entity):
    """
    Auto-generated from cstrike.fgd, line 175.
    Ladder. Players will be able to freely along this brush, as if it was a ladder. If you are using a model prop for the visual representation of the ladder in the map, apply the toolsinvisibleladder material to the func_ladder brush.
    """
    def __init__(self, vmf_map: "ValveMap"):
        Entity.__init__(self, "func_ladder", vmf_map)


class FuncPhysboxMultiplayer(Entity):
    """
    Auto-generated from cstrike.fgd, line 182.
    This class is the same as func_physbox, except the runtime collisions use a more bouncy method that avoids the prediction errors normal physics objects get.
    """
    def __init__(self, vmf_map: "ValveMap", damagefilter: str="", ExplodeDamage: float=0, ExplodeRadius: float=0, PerformanceMode=0, BreakModelMessage: str="", parentname: str="", globalname: str="", propdata=0, material=0, explosion=0, gibdir: "Origin"="0 0 0", nodamageforces=0, gibmodel: str="", spawnobject=0, explodemagnitude: int=0, pressuredelay: float=0, targetname: str="", origin: "Origin"="", renderfx=0, rendermode=0, renderamt: int=255, rendercolor: "RGB"="255 255 255", disablereceiveshadows=0, disableshadows=0, _minlight: str="", spawnflags="", Damagetype=0, massScale: float="0", overridescript: str="", damagetoenablemotion: int=0, forcetoenablemotion: float=0, health: int=0, preferredcarryangles: "Origin"="0 0 0", notsolid=0):
        Entity.__init__(self, "func_physbox_multiplayer", vmf_map)


        # Damage Filter : Name of the filter entity that controls which entities can damage us.
        self.damagefilter: str = damagefilter


        # Explosion Damage : If non-zero, when this entity breaks it will create an explosion that causes the specified amount of damage. See also 'Explosion Radius'.
        self.ExplodeDamage: float = ExplodeDamage
        # Explosion Radius : If non-zero, when this entity breaks it will create an explosion with a radius of the specified amount. See also 'Explosion Damage'.
        self.ExplodeRadius: float = ExplodeRadius
        # Performance Mode : Used to limit the amount of gibs produced when this entity breaks, for performance reasons.
        self.PerformanceMode = PerformanceMode
        # Break Model Message : If set, will use this break model message instead of the normal break behavior.
        self.BreakModelMessage: str = BreakModelMessage

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname: str = parentname

        # Global Entity Name : Name by which this entity is linked to another entity in a different map. When the player transitions to a new map, entities in the new map with globalnames matching entities in the previous map will have the previous map's state copied over their state.
        self.globalname: str = globalname

        # Prop Data : Set to the best approximation of the size and material of this entity's brushes. If set, it will override this entity's health and damage taken from various weapons. See the propdata.txt file in the scripts directory of your MOD to get a detailed list of what each entry specifies.
        self.propdata = propdata
        # Material Type : Set to the material type of the brush. Used to decide what sounds to make when damaged, and what gibs to produce when broken.
        self.material = material
        # Gibs Direction : Used to decide which direction to throw gibs when broken.
        self.explosion = explosion
        # Precise Gib Direction : Specifies the direction to throw gibs when this breakable breaks. Be sure to select Use Precise Gib Dir in the Gibs Direction field!
        self.gibdir: "Origin" = gibdir
        # Damaging it Doesn't Push It : Used to determine whether or not damage should cause the brush to move.
        self.nodamageforces = nodamageforces
        # Gib Model : Used by HL1Port to specify a custom gib model to break into, overriding the 'Material Type'.
        self.gibmodel: str = gibmodel
        # Spawn On Break : When broken, an entity of the selected type will be created.
        self.spawnobject = spawnobject
        # Explode Magnitude : If non-zero, when this entity breaks it will create an explosion that causes the specified amount of damage.
        self.explodemagnitude: int = explodemagnitude
        # Pressure Delay : Delay, in seconds, after 'broken' by pressure before breaking apart (allows for sound to play before breaking apart).
        self.pressuredelay: float = pressuredelay

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Origin (X Y Z) : The position of this entity's center in the world. Rotating entities typically rotate around their origin.
        self.origin: "Origin" = origin

        # Render FX : 
        self.renderfx = renderfx

        # Render Mode : Used to set a non-standard rendering mode on this entity. See also 'FX Amount' and 'FX Color'.
        self.rendermode = rendermode
        # FX Amount (0 - 255) : The FX amount is used by the selected Render Mode.
        self.renderamt: int = renderamt
        # FX Color (R G B) : The FX color is used by the selected Render Mode.
        self.rendercolor: "RGB" = rendercolor
        # Disable Receiving Shadows : 
        self.disablereceiveshadows = disablereceiveshadows

        # Disable shadows : 
        self.disableshadows = disableshadows

        # Minimum Light Level : The minimum level of ambient light that hits this brush.
        self._minlight: str = _minlight
        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags
        # Impact Damage Type : 
        self.Damagetype = Damagetype
        # Mass Scale : A scale multiplier for the object's mass.
        self.massScale: float = massScale
        # Override Parameters : A list of physics key/value pairs that are usually in a physics prop .qc file. Format is 'key,value,key,value,etc'.
        self.overridescript: str = overridescript
        # Health Level to Override Motion : If specified, this object will start motion disabled. Once its health has dropped below this specified amount, it will enable motion.
        self.damagetoenablemotion: int = damagetoenablemotion
        # Physics Impact Force to Override Motion : If specified, this object will start motion disabled. Any impact that imparts a force greater than this value on the physbox will enable motion.
        self.forcetoenablemotion: float = forcetoenablemotion
        # Strength : Number of points of damage to take before breaking.  0 means don't break.
        self.health: int = health
        # Preferred Player-carry Angles : If the 'Use Preferred Carry Angles' spawnflag is set, this angle is the angle which the object should orient to when the player picks it up, with the physgun or +USE.
        self.preferredcarryangles: "Origin" = preferredcarryangles
        # Not solid to world : 
        self.notsolid = notsolid


        self.auto_properties.extend(["damagefilter", "ExplodeDamage", "ExplodeRadius", "PerformanceMode", "BreakModelMessage", "parentname", "globalname", "propdata", "material", "explosion", "gibdir", "nodamageforces", "gibmodel", "spawnobject", "explodemagnitude", "pressuredelay", "targetname", "origin", "renderfx", "rendermode", "renderamt", "rendercolor", "disablereceiveshadows", "disableshadows", "_minlight", "spawnflags", "Damagetype", "massScale", "overridescript", "damagetoenablemotion", "forcetoenablemotion", "health", "preferredcarryangles", "notsolid"])


class FuncTerritoryRespawnArea(Entity):
    """
    Auto-generated from cstrike.fgd, line 291.
    Players will respawn inside this area.
    """
    def __init__(self, vmf_map: "ValveMap", targetname: str=""):
        Entity.__init__(self, "func_territory_respawn_area", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname


        self.auto_properties.extend(["targetname"])


class HostageEntity(Entity):
    """
    Auto-generated from cstrike.fgd, line 78.
    Hostage. A hostage NPC will spawn at this point.\n\nThere are usually four hostages placed in each hostage rescue map. The model for each Hostage is randomly chosen.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0", HostageType=0):
        Entity.__init__(self, "hostage_entity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Hostage Model (int) : Not used. Hostage models are chosen randomly by the game.
        self.HostageType = HostageType

        self.auto_properties.extend(["origin", "angles", "HostageType"])


class InfoMapParameters(Entity):
    """
    Auto-generated from cstrike.fgd, line 103.
    Map parameters. Used to set which teams can buys, and the C4 bomb detonation radius.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", buying=0, bombradius: float=500):
        Entity.__init__(self, "info_map_parameters", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Teams that can buy : 
        self.buying = buying
        # C4 Explosion Radius : Overrides the default radius of the explosion when the C4 bomb explodes. Max range is 2048
        self.bombradius: float = bombradius

        self.auto_properties.extend(["origin", "targetname", "angles", "buying", "bombradius"])


class InfoPlayerCounterterrorist(Entity):
    """
    Auto-generated from cstrike.fgd, line 60.
    This entity marks the start point for counter-terrorists. One of these needs to be placed for each team member. 20 start points is typical. Should be placed at least 128 units away from each other and surrounding walls
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0"):
        Entity.__init__(self, "info_player_counterterrorist", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles


        self.auto_properties.extend(["origin", "angles"])


class InfoPlayerLogo(Entity):
    """
    Auto-generated from cstrike.fgd, line 72.
    This is for logo maps for demos. All players will spawn here, and there will be no class menu, team menu, or HUD.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0"):
        Entity.__init__(self, "info_player_logo", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles


        self.auto_properties.extend(["origin", "angles"])


class InfoPlayerTerrorist(Entity):
    """
    Auto-generated from cstrike.fgd, line 66.
    This entity marks the start point for terrorists. One of these needs to be placed for each team member. 20 start points is typical. Should be placed at least 128 units away from each other and surrounding walls.
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0"):
        Entity.__init__(self, "info_player_terrorist", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles


        self.auto_properties.extend(["origin", "angles"])


class InfoTerritoryControlBank(Entity):
    """
    Auto-generated from cstrike.fgd, line 266.
    Bank Territory Control Point
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_bank", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlBarracks(Entity):
    """
    Auto-generated from cstrike.fgd, line 260.
    Barracks Territory Control Point
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_barracks", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlCounterterrorist(Entity):
    """
    Auto-generated from cstrike.fgd, line 254.
    Counter-Terrorists' Base Territory Point (Non-Capturable)
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_counterterrorist", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlEncryption(Entity):
    """
    Auto-generated from cstrike.fgd, line 272.
    Encryption Center Territory Control Point
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_encryption", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlHospital(Entity):
    """
    Auto-generated from cstrike.fgd, line 240.
    Hospital Territory Control Point
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_hospital", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlSurveillance(Entity):
    """
    Auto-generated from cstrike.fgd, line 278.
    Surveillance Center Territory Control Point
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_surveillance", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoTerritoryControlTerrorist(Entity):
    """
    Auto-generated from cstrike.fgd, line 247.
    Terrorists' Base Territory Point (Non-Capturable)
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", respawn_area: str="", buyzone: str=""):
        Entity.__init__(self, "info_territory_control_terrorist", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # Respawn area name : 
        self.respawn_area: str = respawn_area
        # Buy Zone name : 
        self.buyzone: str = buyzone


        self.auto_properties.extend(["origin", "targetname", "angles", "respawn_area", "buyzone"])


class InfoViewParameters(Entity):
    """
    Auto-generated from cstrike.fgd, line 92.
    This entity selects whether or not this level uses the Half-Life 2 view parameters (eye height: 64, FOV: 75) or the old Counter-Strike settings (eye height: 53.5, FOV: 90).
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", angles: "Origin"="0 0 0", ViewMode=0):
        Entity.__init__(self, "info_view_parameters", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # View Mode : 
        self.ViewMode = ViewMode

        self.auto_properties.extend(["origin", "angles", "ViewMode"])


class ItemDefuser(Entity):
    """
    Auto-generated from cstrike.fgd, line 136.
    Defuse Kit
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "item_defuser", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class PointSurroundtest(Entity):
    """
    Auto-generated from cstrike.fgd, line 224.
    
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str=""):
        Entity.__init__(self, "point_surroundtest", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname


        self.auto_properties.extend(["origin", "targetname"])


class PointTerritoryControlRules(Entity):
    """
    Auto-generated from cstrike.fgd, line 285.
    
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", respawntime: float=30):
        Entity.__init__(self, "point_territory_control_rules", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Wave Respawn Time : Respawn time in seconds.
        self.respawntime: float = respawntime

        self.auto_properties.extend(["origin", "targetname", "respawntime"])


class WeaponAk47(Entity):
    """
    Auto-generated from cstrike.fgd, line 156.
    CV-47
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_ak47", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponAug(Entity):
    """
    Auto-generated from cstrike.fgd, line 160.
    Bullpup
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_aug", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponAwp(Entity):
    """
    Auto-generated from cstrike.fgd, line 165.
    Magnum Sniper Rifle
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_awp", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponC4(Entity):
    """
    Auto-generated from cstrike.fgd, line 137.
    C4 Bomb
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_c4", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponDeagle(Entity):
    """
    Auto-generated from cstrike.fgd, line 142.
    Night Hawk .50C
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_deagle", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponElite(Entity):
    """
    Auto-generated from cstrike.fgd, line 144.
    .40 Dual Elites
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_elite", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponFamas(Entity):
    """
    Auto-generated from cstrike.fgd, line 158.
    Clarion 5.56
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_famas", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponFiveseven(Entity):
    """
    Auto-generated from cstrike.fgd, line 143.
    ES Five-Seven
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_fiveseven", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponFlashbang(Entity):
    """
    Auto-generated from cstrike.fgd, line 132.
    Flashbang
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_flashbang", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponG3sg1(Entity):
    """
    Auto-generated from cstrike.fgd, line 163.
    D3/AU-1 Semi-Auto Sniper Rifle
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_g3sg1", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponGalil(Entity):
    """
    Auto-generated from cstrike.fgd, line 155.
    IDF Defender
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_galil", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponGlock(Entity):
    """
    Auto-generated from cstrike.fgd, line 139.
    9X19mm Sidearm
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_glock", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponHegrenade(Entity):
    """
    Auto-generated from cstrike.fgd, line 133.
    HE Grenade
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_hegrenade", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponKnife(Entity):
    """
    Auto-generated from cstrike.fgd, line 130.
    Knife
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_knife", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponM249(Entity):
    """
    Auto-generated from cstrike.fgd, line 167.
    ES M249 Para
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_m249", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponM3(Entity):
    """
    Auto-generated from cstrike.fgd, line 146.
    Leone 12 Gauge Super
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_m3", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponM4a1(Entity):
    """
    Auto-generated from cstrike.fgd, line 159.
    Maverick M4A1 Carbine
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_m4a1", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponMac10(Entity):
    """
    Auto-generated from cstrike.fgd, line 153.
    Ingram MAC-10
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_mac10", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponMp5navy(Entity):
    """
    Auto-generated from cstrike.fgd, line 150.
    K&M Sub-Machine Gun
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_mp5navy", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponP228(Entity):
    """
    Auto-generated from cstrike.fgd, line 141.
    228 Compact
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_p228", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponP90(Entity):
    """
    Auto-generated from cstrike.fgd, line 152.
    ES C90
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_p90", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponScout(Entity):
    """
    Auto-generated from cstrike.fgd, line 162.
    Schmidt Scout
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_scout", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponSg550(Entity):
    """
    Auto-generated from cstrike.fgd, line 164.
    Krieg 550 Commando
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_sg550", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponSg552(Entity):
    """
    Auto-generated from cstrike.fgd, line 157.
    Krieg 552 Commando
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_sg552", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponSmokegrenade(Entity):
    """
    Auto-generated from cstrike.fgd, line 134.
    Smoke Grenade
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_smokegrenade", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponTmp(Entity):
    """
    Auto-generated from cstrike.fgd, line 149.
    Schmidt Machine Pistol
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_tmp", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponUmp45(Entity):
    """
    Auto-generated from cstrike.fgd, line 151.
    K&M UMP45
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_ump45", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponUsp(Entity):
    """
    Auto-generated from cstrike.fgd, line 140.
    K&M .45 Tactical
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_usp", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


class WeaponXm1014(Entity):
    """
    Auto-generated from cstrike.fgd, line 147.
    Leone YG1265 Auto Shotgun
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", angles: "Origin"="0 0 0", spawnflags=""):
        Entity.__init__(self, "weapon_xm1014", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles: "Origin" = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags


        self.auto_properties.extend(["origin", "targetname", "angles", "spawnflags"])


