"""
Helper classes for creating maps in any Source Engine game that uses ep2.fgd.
This file was auto-generated by import_fgd.py on 2020-01-15 18:10:33.456211.
"""

from vmflib2.vmf import *


class Demo1Entity(Entity):
    """
    Auto-generated from ep2.fgd, line 9.
    Demo 1 : An entity which shakes entities near it
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", amplitude: float="40", radius: float="500"):
        Entity.__init__(self, "demo1_entity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Amplitude : The magnitude of the force to apply to nearby physics objects
        self.amplitude: float = amplitude
        # Effect Radius : The radius around this entity in which to affect objects.
        self.radius: float = radius

        self.auto_properties.extend(["origin", "amplitude", "radius"])


class Demo2Entity(Entity):
    """
    Auto-generated from ep2.fgd, line 18.
    Demo 2 : An entity which shakes entities near it
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", amplitude: float="40", radius: float="150", effect_name: str="", effect2_name: str=""):
        Entity.__init__(self, "demo2_entity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Amplitude : The magnitude of the force to apply to nearby physics objects
        self.amplitude: float = amplitude
        # Effect Radius : The radius around this entity in which to affect objects.
        self.radius: float = radius
        # Particle System Name : Particle system to periodically emit at the entity origin
        self.effect_name: str = effect_name
        # Particle System Name #2 : 2nd Particle system to periodically emit at the entity origin
        self.effect2_name: str = effect2_name

        self.auto_properties.extend(["origin", "amplitude", "radius", "effect_name", "effect2_name"])


class Demo3Entity(Entity):
    """
    Auto-generated from ep2.fgd, line 29.
    Demo 3 : An entity which shakes entities near it
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", amplitude: float="40", radius: float="150", effect_name: str=""):
        Entity.__init__(self, "demo3_entity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Amplitude : The magnitude of the force to apply to nearby physics objects
        self.amplitude: float = amplitude
        # Effect Radius : The radius around this entity in which to affect objects.
        self.radius: float = radius
        # Particle System Name : Particle system to periodically emit on nearby objects
        self.effect_name: str = effect_name

        self.auto_properties.extend(["origin", "amplitude", "radius", "effect_name"])


class Demo4Entity(Entity):
    """
    Auto-generated from ep2.fgd, line 39.
    Demo 4 : An entity which shakes entities near it
    """
    def __init__(self, vmf_map: "ValveMap", targetname: str="", amplitude: float="40", radius: float="150"):
        Entity.__init__(self, "demo4_entity", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # Amplitude : The magnitude of the force to apply to nearby physics objects
        self.amplitude: float = amplitude
        # Effect Radius : The radius around this entity in which to affect objects.
        self.radius: float = radius

        self.auto_properties.extend(["targetname", "amplitude", "radius"])


class Demo5Entity(Entity):
    """
    Auto-generated from ep2.fgd, line 50.
    Demo 5 : An entity which shakes entities near it
    """
    def __init__(self, vmf_map: "ValveMap", origin: "Origin"="0 0 0", targetname: str="", model: str="", skin: int=0, modelscale: float="1.0", disableshadows=0, amplitude: float="40", radius: float="150", effect_name: str=""):
        Entity.__init__(self, "demo5_entity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin: "Origin" = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname: str = targetname

        # World Model : 
        self.model: str = model
        # Skin : Some models have multiple versions of their textures, called skins. Set this to a number other than 0 to use that skin instead of the default.
        self.skin: int = skin
        # Model Scale : A multiplier for the size of the model.
        self.modelscale: float = modelscale
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows

        # Amplitude : The magnitude of the force to apply to nearby physics objects
        self.amplitude: float = amplitude
        # Effect Radius : The radius around this entity in which to affect objects.
        self.radius: float = radius
        # Particle System Name : Particle system to periodically emit on nearby objects
        self.effect_name: str = effect_name

        self.auto_properties.extend(["origin", "targetname", "model", "skin", "modelscale", "disableshadows", "amplitude", "radius", "effect_name"])


