"""
Helper classes for creating maps in any Source Engine game that uses garrysmod.fgd.
This file was auto-generated by import_fgd.py on 2018-06-20 16:16:59.005379.
"""

from vmflib2.vmf import *


class EnvProjectedtexture(Entity):
    """
    Auto-generated from garrysmod.fgd, line 19.
    Projected texture entity.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", spawnflags="", target="", lightfov="90.0", nearz="4.0", farz="750.0", enableshadows=1, lightonlytarget=0, lightworld=1, lightcolor="255 255 255", lightstrength="1.0", cameraspace=0, texturename="effects/flashlight001", textureframe=0):
        Entity.__init__(self, "env_projectedtexture", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags
        # target : target
        self.target = target
        # FOV : FOV
        self.lightfov = lightfov
        # NearZ : Near Z for projected texture
        self.nearz = nearz
        # FarZ : Far Z for projected texture
        self.farz = farz
        # Enable Shadows : Enables/disables shadows from this projected texture.
        self.enableshadows = enableshadows
        # Light Only Target : Limit flashlight effect to only effect target entity.
        self.lightonlytarget = lightonlytarget
        # Light World : Control whether flashlight effects static world geometry.
        self.lightworld = lightworld
        # Light Color : Light Color RGB-Intensity
        self.lightcolor = lightcolor
        # Light Strength : How bright the light appears
        self.lightstrength = lightstrength
        # Camera Space : Angles are interpreted as being relative to camera.
        self.cameraspace = cameraspace
        # Texture Name : The name of the texture to use
        self.texturename = texturename
        # Texture Frame : The frame of the texture
        self.textureframe = textureframe

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "spawnflags", "target", "lightfov", "nearz", "farz", "enableshadows", "lightonlytarget", "lightworld", "lightcolor", "lightstrength", "cameraspace", "texturename", "textureframe"])


class EnvSkypaint(Entity):
    """
    Auto-generated from garrysmod.fgd, line 62.
    Control the sky colours
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", topcolor="0.2 0.5 1.0", bottomcolor="0.8 1.0 1.0", fadebias="1.0", sunsize="2.0", sunnormal="0.4 0.0 0.01", sunposmethod=0, suncolor="0.2 0.1 0.0", duskscale="1.0", duskintensity="1.0", duskcolor="1.0 0.2 0.0", drawstars=0, startexture="skybox/starfield", starscale="0.5", starfade="1.0", starspeed="0.01", hdrscale="0.66"):
        Entity.__init__(self, "env_skypaint", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Sky Top Color : The colour of the top of the sky
        self.topcolor = topcolor
        # Sky Bottom Color : The colour of the bottom of the sky
        self.bottomcolor = bottomcolor
        # Sky Fade Bias : Controls the bias of the fade between top/bottom (1.0 is even)
        self.fadebias = fadebias
        # Sun Size : Controls the size of the sun glow
        self.sunsize = sunsize
        # Sun Normal : The position of the sun, expressed as a normal from the center of the world
        self.sunnormal = sunnormal
        # Sun Position Method : How should we determine the position of the sun?
        self.sunposmethod = sunposmethod
        # Sun Color : The color of the sun glow (this is additive)
        self.suncolor = suncolor
        # Dusk Scale : The size of the dusk effect (colouring of the horizon)
        self.duskscale = duskscale
        # Dusk Intensity : How powerful the dusk effect is
        self.duskintensity = duskintensity
        # Dusk Color : The color of the dusk effect
        self.duskcolor = duskcolor
        # Draw Stars : 
        self.drawstars = drawstars
        # Star Texture : The star texture
        self.startexture = startexture
        # Star Scale : How big the star texture should be
        self.starscale = starscale
        # Star Fade : Fade the star texture towards the horizon
        self.starfade = starfade
        # Star Speed : How fast the star texture should scroll across the sky
        self.starspeed = starspeed
        # HDR Scale : When rendering your skybox in HDR mode, output will be scaled by this amount.
        self.hdrscale = hdrscale

        self.auto_properties.extend(["origin", "targetname", "topcolor", "bottomcolor", "fadebias", "sunsize", "sunnormal", "sunposmethod", "suncolor", "duskscale", "duskintensity", "duskcolor", "drawstars", "startexture", "starscale", "starfade", "starspeed", "hdrscale"])


class FuncLadder(Entity):
    """
    Auto-generated from garrysmod.fgd, line 5.
    Ladder. Players will be able to move freely along this brush, as if it was a ladder.Apply the toolsinvisibleladder material to a func_ladder brush.
    """
    def __init__(self, vmf_map):
        Entity.__init__(self, "func_ladder", vmf_map)


class LuaRun(Entity):
    """
    Auto-generated from garrysmod.fgd, line 11.
    Runs Lua Code
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", Code=""):
        Entity.__init__(self, "lua_run", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Code : Lua code to run when triggered
        self.Code = Code

        self.auto_properties.extend(["origin", "targetname", "Code"])


