"""
Helper classes for creating maps in any Source Engine game that uses garrysmod.fgd.
This file was auto-generated by import_fgd.py on 2018-06-20 02:34:07.856929.
"""

from vmflib2.vmf import *


class EnvProjectedtexture(Entity):
    """
    Auto-generated from garrysmod.fgd, line 19.
    Projected texture entity.
    """
    def __init__(self, vmf_map):
        Entity.__init__(self, "env_projectedtexture", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = ""

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = ""

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = "0 0 0" 

        # TODO: Replace this filler. : TODO: Replace this filler.
        self.spawnflags = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.target = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.lightfov = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.nearz = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.farz = ""
        # Enable Shadows : Enables/disables shadows from this projected texture.
        self.enableshadows = 1 
        # Light Only Target : Limit flashlight effect to only effect target entity.
        self.lightonlytarget = 0 
        # Light World : Control whether flashlight effects static world geometry.
        self.lightworld = 1 
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.lightcolor = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.lightstrength = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.cameraspace = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.texturename = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.textureframe = ""

        self.auto_properties.extend(["targetname", "parentname", "angles", "spawnflags", "target", "lightfov", "nearz", "farz", "enableshadows", "lightonlytarget", "lightworld", "lightcolor", "lightstrength", "cameraspace", "texturename", "textureframe"])


class EnvSkypaint(Entity):
    """
    Auto-generated from garrysmod.fgd, line 62.
    Control the sky colours
    """
    def __init__(self, vmf_map):
        Entity.__init__(self, "env_skypaint", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = ""

        # TODO: Replace this filler. : TODO: Replace this filler.
        self.topcolor = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.bottomcolor = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.fadebias = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.sunsize = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.sunnormal = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.sunposmethod = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.suncolor = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.duskscale = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.duskintensity = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.duskcolor = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.drawstars = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.startexture = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.starscale = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.starfade = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.starspeed = ""
        # TODO: Replace this filler. : TODO: Replace this filler.
        self.hdrscale = ""

        self.auto_properties.extend(["targetname", "topcolor", "bottomcolor", "fadebias", "sunsize", "sunnormal", "sunposmethod", "suncolor", "duskscale", "duskintensity", "duskcolor", "drawstars", "startexture", "starscale", "starfade", "starspeed", "hdrscale"])


class FuncLadder(Entity):
    """
    Auto-generated from garrysmod.fgd, line 5.
    Ladder. Players will be able to move freely along this brush, as if it was a ladder.Apply the toolsinvisibleladder material to a func_ladder brush.
    """
    def __init__(self, vmf_map):
        Entity.__init__(self, "func_ladder", vmf_map)


class LuaRun(Entity):
    """
    Auto-generated from garrysmod.fgd, line 11.
    Runs Lua Code
    """
    def __init__(self, vmf_map):
        Entity.__init__(self, "lua_run", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = ""

        # Code : Lua code to run when triggered
        self.Code = "" 

        self.auto_properties.extend(["targetname", "Code"])


