"""
Helper classes for creating maps in any Source Engine game that uses empires.fgd.
This file was auto-generated by import_fgd.py on 2018-06-20 16:16:58.762029.
"""

from vmflib2.vmf import *


class EmpBuildingImpAirfactory(Entity):
    """
    Auto-generated from empires.fgd, line 518.
    The air factory allows players to build aircraft.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/AirFactory/imp_airfactory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_airfactory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingImpArmory(Entity):
    """
    Auto-generated from empires.fgd, line 548.
    The armory supplies ammo and health to players.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/Armory/imp_armory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_armory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingImpBarracks(Entity):
    """
    Auto-generated from empires.fgd, line 578.
    The barracks spawns players and allows for dynamic class changes.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/Buildings/Barracks/imp_barracks.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_barracks", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt"])


class EmpBuildingImpMgturret(Entity):
    """
    Auto-generated from empires.fgd, line 750.
    The MG turret fires on enemy infantry.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/turrets/mg_lvl1/imp_turret_mg_lvl1.mdl", startBuilt=1, level=1):
        Entity.__init__(self, "emp_building_imp_mgturret", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt
        # Level : Determines what level the turret is.
        self.level = level

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt", "level"])


class EmpBuildingImpMlturret(Entity):
    """
    Auto-generated from empires.fgd, line 794.
    The ML turret fires on enemy buildings and vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/turrets/ml_lvl1/imp_turret_ml_lvl1.mdl", startBuilt=1, level=1):
        Entity.__init__(self, "emp_building_imp_mlturret", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt
        # Level : Determines what level the turret is.
        self.level = level

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt", "level"])


class EmpBuildingImpRadar(Entity):
    """
    Auto-generated from empires.fgd, line 608.
    The radar provides access to research and detects enemy units.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/Radar/imp_radar.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_radar", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingImpRefinery(Entity):
    """
    Auto-generated from empires.fgd, line 638.
    The refinery extracts minerals from the ground for purchasing vehicles and buildings.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/Refinery/imp_refinery.mdl", target="", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_refinery", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Resource Node : This is the resource node the refinery is built on.
        self.target = target
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "target", "startBuilt"])


class EmpBuildingImpRepairstation(Entity):
    """
    Auto-generated from empires.fgd, line 672.
    The repair station repairs vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/RepairPad/imp_repairpad.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_repairstation", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingImpVehiclefactory(Entity):
    """
    Auto-generated from empires.fgd, line 838.
    The vehicle factory produces vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/Imperial/Buildings/VehicleFactory/imp_vehiclefactory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_imp_vehiclefactory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingNfAirfactory(Entity):
    """
    Auto-generated from empires.fgd, line 533.
    The air factory allows players to build aircraft.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/AirFactory/nf_airfactory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_airfactory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingNfArmory(Entity):
    """
    Auto-generated from empires.fgd, line 563.
    The armory supplies ammo and health to players.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/Armory/nf_armory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_armory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingNfBarracks(Entity):
    """
    Auto-generated from empires.fgd, line 593.
    The barracks spawns players and allows for dynamic class changes.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/NF/Buildings/Barracks/nf_barracks.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_barracks", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt"])


class EmpBuildingNfMgturret(Entity):
    """
    Auto-generated from empires.fgd, line 772.
    The MG turret fires on enemy infantry.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/NF/turrets/mg_lvl1/nf_turret_mg_lvl1.mdl", startBuilt=1, level=1):
        Entity.__init__(self, "emp_building_nf_mgturret", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt
        # Level : Determines what level the turret is.
        self.level = level

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt", "level"])


class EmpBuildingNfMlturret(Entity):
    """
    Auto-generated from empires.fgd, line 816.
    The ML turret fires on enemy buildings and vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/NF/turrets/ml_lvl1/nf_turret_ml_lvl1.mdl", startBuilt=1, level=1):
        Entity.__init__(self, "emp_building_nf_mlturret", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt
        # Level : Determines what level the turret is.
        self.level = level

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt", "level"])


class EmpBuildingNfRadar(Entity):
    """
    Auto-generated from empires.fgd, line 623.
    The radar provides access to research and detects enemy units.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/Radar/nf_radar.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_radar", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingNfRefinery(Entity):
    """
    Auto-generated from empires.fgd, line 655.
    The refinery extracts minerals from the ground for purchasing vehicles and buildings.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/Refinery/nf_refinery.mdl", target="", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_refinery", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Resource Node : This is the resource node the refinery is built on.
        self.target = target
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "target", "startBuilt"])


class EmpBuildingNfRepairstation(Entity):
    """
    Auto-generated from empires.fgd, line 687.
    The repair station repairs vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/RepairPad/nf_repairpad.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_repairstation", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpBuildingNfVehiclefactory(Entity):
    """
    Auto-generated from empires.fgd, line 853.
    The vehicle factory produces vehicles.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="models/NF/Buildings/VehicleFactory/nf_vehiclefactory.mdl", startBuilt=1):
        Entity.__init__(self, "emp_building_nf_vehiclefactory", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "startBuilt"])


class EmpCapModel(Entity):
    """
    Auto-generated from empires.fgd, line 166.
    An entity with three separate model states for use with capture points: neutral, Northern Faction owned, and Brenodi Empire owned
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", pointNumber=0, fademindist=-1, fademaxdist=0, disableshadows=0, model="models/Common/props_system/flagpole01_neutral.mdl", model2="", model3="", VisibleOnMap=1):
        Entity.__init__(self, "emp_cap_model", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Neutral Model : 
        self.model = model
        # Northern Faction Model : 
        self.model2 = model2
        # Brenodi Empire Model : 
        self.model3 = model3
        # Visible On Minimap : If yes, a flag of the owning team will appear at this entity's location on the minimap.
        self.VisibleOnMap = VisibleOnMap

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "pointNumber", "fademindist", "fademaxdist", "disableshadows", "model", "model2", "model3", "VisibleOnMap"])


class EmpCapPoint(Entity):
    """
    Auto-generated from empires.fgd, line 4.
    Empires capture point.
    """
    def __init__(self, vmf_map, targetname="", parentname="", pointNumber=0, locationName="Capture Point 1", timeToCap=5, timeToNeutral=5, playersRequiredNF=1, playersRequiredImp=1, canNFCap=0, canImpCap=0, teamOwner=0, linearMap=0, resToGiveNF=0, resToGiveImp=0, reinfToTakeNF=0, reinfToTakeImp=0):
        Entity.__init__(self, "emp_cap_point", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Number of this Capture Point : '1' is the first NF flag.  The highest numbered flag is the IMP's first flag.  Each capture point must be given a sequential number identifier to handle automatically enabling the next capture point and disabling the previous one.  A number of '0' will disable this feature requiring manual enabling/disabling of the next capture point.
        self.pointNumber = pointNumber
        # Location Name : The name of the capture point displayed to the player.
        self.locationName = locationName
        # Time To Capture : The amount of time (in seconds) required to be the only team touching to capture.
        self.timeToCap = timeToCap
        # Time To Neutral : The amount of time (in seconds) required to turn an enemy controlled flag neutral.
        self.timeToNeutral = timeToNeutral
        # Players Required (NF) : The number of players required to capture of team Northern Faction.
        self.playersRequiredNF = playersRequiredNF
        # Players Required (Imp) : The number of players required to capture of team Brenodi Empire.
        self.playersRequiredImp = playersRequiredImp
        # NF Cappable : Can the capture point be captured by the Northern Faction?
        self.canNFCap = canNFCap
        # Imp Cappable : Can the capture point be captured by the Brenodi Empire?
        self.canImpCap = canImpCap
        # Owned By : The initial owner of this capture point.
        self.teamOwner = teamOwner
        # Linear Capture : If yes, then the next capture point (based on capture point number) will be enabled for capture while the previous will be disabled to force capture points to be captured in a linear order.  Otherwise, the capture point number will only be utilized to enable/disable entities associated with this capture point.
        self.linearMap = linearMap
        # Resources to Give the NF : Number of resources to give to the Northern Faction per second when they have it captured.
        self.resToGiveNF = resToGiveNF
        # Resources to Give the Imperials : Number of resources to give to the Brenodi Empire per second when they have it captured.
        self.resToGiveImp = resToGiveImp
        # Reinforcements to take NF : Number of reinforcements to take from Northern Faction when the Brenodi Empire have it captured.
        self.reinfToTakeNF = reinfToTakeNF
        # Reinforcements to take Imperials : Number of reinforcements to take from the Brenodi Empire when the Northern Faction have it captured.
        self.reinfToTakeImp = reinfToTakeImp

        self.auto_properties.extend(["targetname", "parentname", "pointNumber", "locationName", "timeToCap", "timeToNeutral", "playersRequiredNF", "playersRequiredImp", "canNFCap", "canImpCap", "teamOwner", "linearMap", "resToGiveNF", "resToGiveImp", "reinfToTakeNF", "reinfToTakeImp"])


class EmpCommRestrict(Entity):
    """
    Auto-generated from empires.fgd, line 897.
    This brush will restrict commanders from building any item that touches it.
    """
    def __init__(self, vmf_map, targetname="", parentname=""):
        Entity.__init__(self, "emp_comm_restrict", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname


        self.auto_properties.extend(["targetname", "parentname"])


class EmpCommanderAutoTarget(Entity):
    """
    Auto-generated from empires.fgd, line 1539.
    An entity that sets commander targets on entities passed in with SetPlayerTarget
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", targetEntityName=""):
        Entity.__init__(self, "emp_commander_auto_target", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Target Entity Name : The name of the entity to target.
        self.targetEntityName = targetEntityName

        self.auto_properties.extend(["origin", "targetname", "targetEntityName"])


class EmpEngCamera(Entity):
    """
    Auto-generated from empires.fgd, line 702.
    The ENG Camera. All team choices must be the same for this camera.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/imperial/turrets/camera/imp_camera.mdl", startBuilt=1, teamNum=3, TeamNumber=3, SetTeam=3, Sequence=3, PlaybackRate="1", NewSequenceParity=1, ReseteventsParity=1):
        Entity.__init__(self, "emp_eng_camera", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Faction Model : NF or BE camera model
        self.model = model
        # Fully Built? : If yes, then the building will start with full health and be fully functional.  If no, then an engineer must repair it to full health before it functions.
        self.startBuilt = startBuilt
        # Faction set 1 : Which faction will own the camera.
        self.teamNum = teamNum
        # Faction set 2 : Which faction will own the camera.
        self.TeamNumber = TeamNumber
        # Faction set 3 : Which faction will own the camera.
        self.SetTeam = SetTeam
        # Faction set 4 : Which faction will own the camera.
        self.Sequence = Sequence
        # Unknown : Required to work in 2.3
        self.PlaybackRate = PlaybackRate
        # Unknown : Required to work in 2.3
        self.NewSequenceParity = NewSequenceParity
        # Unknown : Required to work in 2.3
        self.ReseteventsParity = ReseteventsParity

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "startBuilt", "teamNum", "TeamNumber", "SetTeam", "Sequence", "PlaybackRate", "NewSequenceParity", "ReseteventsParity"])


class EmpEngMapBrush(Entity):
    """
    Auto-generated from empires.fgd, line 274.
    An entity which when enabled can be built by the owning team's engineer into a defensive structure such as a wall or barricade.
    """
    def __init__(self, vmf_map, targetname="", parentname="", pointNumber=0, fademindist=-1, fademaxdist=0, initialOwner=0, changeOwner=0, raiseOnBuild=0, STFU=0, visibleToEnemy=0, timeToRespawn=120, Health=25, MaximumHealth=100, repairMultiplier=1, damageMultiplier=1, GrenadierOnly=0, SolidOnRespawn=0):
        Entity.__init__(self, "emp_eng_map_brush", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Initial Owner : This is the team that initially owns the object.  This should only be set for objects that are not associated with a control point.
        self.initialOwner = initialOwner
        # Changes Ownership : This option affects automatic enabling/disabling from an automated capture point.  If no, this object will be disabled when the other team holds the capture point and enable when the initial owner recaptures the point.  If yes, this object will change teams as the capture point is captured.
        self.changeOwner = changeOwner
        # Raise Object On Build : If yes, this entity will start at only 25% of its final height and will raise up to its full height as it's built.  It's a good effect for tall objects like walls.
        self.raiseOnBuild = raiseOnBuild
        # Solid On Spawn : Does this entity start solid or does it need to be fully built first?
        self.STFU = STFU
        # Visible To Enemy Team When Not Solid : Can players of the enemy team see this object if it hasn't been fully built yet (if 'Solid On Spawn' is yes [above], then this is ignored).
        self.visibleToEnemy = visibleToEnemy
        # Time To Respawn : Time in seconds for the object to respawn and be buildable again after being destroyed.  A time of 0 seconds will never respawn until it is disabled and/or changes teams.
        self.timeToRespawn = timeToRespawn
        # Structure's Initial Health : The initial health of the object on spawn.
        self.Health = Health
        # Structure's Max Health : The maximum health of the object and when it becomes fully built after being repaired by an engineer.
        self.MaximumHealth = MaximumHealth
        # Repair multiplier : All repairs done to this object will be multiplied by this number. (Integer > 0)
        self.repairMultiplier = repairMultiplier
        # Damage multiplier : All damage done to this object will be multiplied by this number. (Integer > 0)
        self.damageMultiplier = damageMultiplier
        # Only Grenadier Can Harm : If yes, then only the grenadier can harm this object, and his rpg does normal damage.  Use this for creating obstacles in your map that only grenadiers can get through.  If no, then enemy engineers can deconstruct it, and all blast damage does a reduced amount of damage to it.
        self.GrenadierOnly = GrenadierOnly
        # Solid On Respawn : After this is destroyed and it respawns, does this entity start solid or does it need to be fully built first?
        self.SolidOnRespawn = SolidOnRespawn

        self.auto_properties.extend(["targetname", "parentname", "pointNumber", "fademindist", "fademaxdist", "initialOwner", "changeOwner", "raiseOnBuild", "STFU", "visibleToEnemy", "timeToRespawn", "Health", "MaximumHealth", "repairMultiplier", "damageMultiplier", "GrenadierOnly", "SolidOnRespawn"])


class EmpEngMapModel(Entity):
    """
    Auto-generated from empires.fgd, line 194.
    An entity which when enabled can be built by the owning team's engineer into a defensive structure such as a wall or barricade.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/Buildings/Walls/imp_wall1.mdl", fademindist=-1, fademaxdist=0, skin=0, pointNumber=0, disableshadows=0, initialOwner=0, changeOwner=0, raiseOnBuild=0, solidOnSpawn=0, visibleToEnemy=0, timeToRespawn=120, Health=25, MaximumHealth=100, repairMultiplier=1, damageMultiplier=1, GrenadierOnly=0, SolidOnRespawn=0):
        Entity.__init__(self, "emp_eng_map_model", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Skin : Some models have multiple versions of their textures, called skins. Set this to a number other than 0 to use that skin instead of the default.
        self.skin = skin
        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Initial Owner : This is the team that initially owns the object.  This should only be set for objects that are not associated with a control point.
        self.initialOwner = initialOwner
        # Changes Ownership : This option affects automatic enabling/disabling from an automated capture point.  If no, this object will be disabled when the other team holds the capture point and enable when the initial owner recaptures the point.  If yes, this object will change teams as the capture point is captured.
        self.changeOwner = changeOwner
        # Raise Object On Build : If yes, this entity will start at only 25% of its final height and will raise up to its full height as it's built.  It's a good effect for tall objects like walls.
        self.raiseOnBuild = raiseOnBuild
        # Solid On Spawn : Does this entity start solid or does it need to be fully built first?
        self.solidOnSpawn = solidOnSpawn
        # Visible To Enemy When Not Solid : Can players of the enemy team see this object if it hasn't been fully built yet (if 'Solid On Spawn' is yes [above], then this is ignored).
        self.visibleToEnemy = visibleToEnemy
        # Time To Respawn : Time in seconds for the object to respawn and be buildable again after being destroyed.  A time of 0 seconds will never respawn until it is disabled and/or changes teams.
        self.timeToRespawn = timeToRespawn
        # Structure's Initial Health : The initial health of the object on spawn.
        self.Health = Health
        # Structure's Max Health : The maximum health of the object and when it becomes fully built after being repaired by an engineer.
        self.MaximumHealth = MaximumHealth
        # Repair multiplier : All repairs done to this object will be multiplied by this number. (Integer > 0)
        self.repairMultiplier = repairMultiplier
        # Damage multiplier : All damage done to this object will be multiplied by this number. (Integer > 0)
        self.damageMultiplier = damageMultiplier
        # Only Grenadier Can Harm : If yes, then only the grenadier can harm this object, and his rpg does normal damage.  Use this for creating obstacles in your map that only grenadiers can get through.  If no, then enemy engineers can deconstruct it, and all blast damage does a reduced amount of damage to it.
        self.GrenadierOnly = GrenadierOnly
        # Solid On Respawn : After this is destroyed and it respawns, does this entity start solid or does it need to be fully built first?
        self.SolidOnRespawn = SolidOnRespawn

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "fademindist", "fademaxdist", "skin", "pointNumber", "disableshadows", "initialOwner", "changeOwner", "raiseOnBuild", "solidOnSpawn", "visibleToEnemy", "timeToRespawn", "Health", "MaximumHealth", "repairMultiplier", "damageMultiplier", "GrenadierOnly", "SolidOnRespawn"])


class EmpEngRestrict(Entity):
    """
    Auto-generated from empires.fgd, line 870.
    This brush will restrict engineers from building any item within it (ammo crates, walls, turrets, camera, and radar).
    """
    def __init__(self, vmf_map, targetname="", parentname="", restrictNF=1, restrictImp=1, turretRestrict=3):
        Entity.__init__(self, "emp_eng_restrict", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Prevent NF Engineer Building : Select restrictions for the Northern Faction engineers from being able to build when touching this brush.
        self.restrictNF = restrictNF
        # Prevent Brenodi Engineer Building : Select restrictions for the Brenodi Empire engineers from being able to build when touching this brush.
        self.restrictImp = restrictImp
        # Prevent turret building : Does not affect the commander
        self.turretRestrict = turretRestrict

        self.auto_properties.extend(["targetname", "parentname", "restrictNF", "restrictImp", "turretRestrict"])


class EmpEnvEmbers(Entity):
    """
    Auto-generated from empires.fgd, line 904.
    An entity used to create a volume in which to spawn fire embers.
    """
    def __init__(self, vmf_map, targetname="", parentname="", angles="0 0 0", particletype=0, density=50, lifetime=4, speed=32, start_size=1, end_size=0, rendercolor="255 255 255", spawnflags=""):
        Entity.__init__(self, "emp_env_embers", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Ember type : 
        self.particletype = particletype
        # Density (particles per second) : 
        self.density = density
        # Particle Lifetime (seconds) : 
        self.lifetime = lifetime
        # Particle Speed (units per second) : 
        self.speed = speed
        # Particle Size On Start : 
        self.start_size = start_size
        # Particle Size On End : 
        self.end_size = end_size
        # Ember Color (R G B) : 
        self.rendercolor = rendercolor
        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags

        self.auto_properties.extend(["targetname", "parentname", "angles", "particletype", "density", "lifetime", "speed", "start_size", "end_size", "rendercolor", "spawnflags"])


class EmpFilterActivatorChassisname(Entity):
    """
    Auto-generated from empires.fgd, line 1470.
    A filter that filters by the chassis name or chassis spotted name of a vehicle
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", Negated="Allow entities that match criteria", filterchassisname="", filterbyspottedname=0):
        Entity.__init__(self, "emp_filter_activator_chassisname", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Filter mode : If set to Allow, only entities who match the criteria will pass the filter. 
        self.Negated = Negated

        # Filter Chassis Name : Filter name must by identical to the name in the script file. Input '!any' to check for any vehicle.
        self.filterchassisname = filterchassisname
        # Check Against : Which name value should be queried?
        self.filterbyspottedname = filterbyspottedname

        self.auto_properties.extend(["origin", "targetname", "Negated", "filterchassisname", "filterbyspottedname"])


class EmpFilterActivatorWeaponname(Entity):
    """
    Auto-generated from empires.fgd, line 1480.
    A filter that filters by the chassis name or chassis spotted name of a vehicle
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", Negated="Allow entities that match criteria", WeaponName=""):
        Entity.__init__(self, "emp_filter_activator_weaponname", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Filter mode : If set to Allow, only entities who match the criteria will pass the filter. 
        self.Negated = Negated

        # Filter Weapon Name : Filter name must by identical to the name in the script file. Input '!any' to check for any vehicle.
        self.WeaponName = WeaponName

        self.auto_properties.extend(["origin", "targetname", "Negated", "WeaponName"])


class EmpImpAmmoCrate(Entity):
    """
    Auto-generated from empires.fgd, line 400.
    Brenodi Empire Ammo Crate which resupplies IMP players with ammo when they 'use' the crate.  It never expires.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/Props/imp_crateammo.mdl", fademindist=-1, fademaxdist=0, disableshadows=0, pointNumber=0, startDisabled=0):
        Entity.__init__(self, "emp_imp_ammo_crate", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Disabled? : If yes, then it will be invisible, not solid, and unusable until enabled by an input.
        self.startDisabled = startDisabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "fademindist", "fademaxdist", "disableshadows", "pointNumber", "startDisabled"])


class EmpImpCommander(Entity):
    """
    Auto-generated from empires.fgd, line 503.
    This entity is the Imperial commander's command tank.  Entering it allows him to drive the vehicle and to play the RTS aspect of the game (base building, issuing orders, etc) using his own unique interface.  The death of this unit ends the game. 
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0"):
        Entity.__init__(self, "emp_imp_commander", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles


        self.auto_properties.extend(["origin", "targetname", "angles"])


class EmpImpHealthCrate(Entity):
    """
    Auto-generated from empires.fgd, line 425.
    Brenodi Empire Ammo Crate which resupplies IMP players with health when they 'use' the crate.  It never expires.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/Imperial/Props/imp_cratehealth.mdl", fademindist=-1, fademaxdist=0, disableshadows=0, pointNumber=0, startDisabled=0):
        Entity.__init__(self, "emp_imp_health_crate", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Disabled? : If yes, then it will be invisible, not solid, and unusable until enabled by an input.
        self.startDisabled = startDisabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "fademindist", "fademaxdist", "disableshadows", "pointNumber", "startDisabled"])


class EmpInfantryRestrict(Entity):
    """
    Auto-generated from empires.fgd, line 928.
    This brush will restrict infantry access based on class and faction.
    """
    def __init__(self, vmf_map, targetname="", parentname="", allowScout=1, allowRifleman=1, allowGrenadier=1, allowEngineer=1, allowNF=1, allowBE=1):
        Entity.__init__(self, "emp_infantry_restrict", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Allow scouts? : 
        self.allowScout = allowScout
        # Allow riflemen? : 
        self.allowRifleman = allowRifleman
        # Allow grenadiers? : 
        self.allowGrenadier = allowGrenadier
        # Allow engineers? : 
        self.allowEngineer = allowEngineer
        # Allow NF? : 
        self.allowNF = allowNF
        # Allow BE? : 
        self.allowBE = allowBE

        self.auto_properties.extend(["targetname", "parentname", "allowScout", "allowRifleman", "allowGrenadier", "allowEngineer", "allowNF", "allowBE"])


class EmpInfoMapOverview(Entity):
    """
    Auto-generated from empires.fgd, line 497.
    This entity determines where a player first entering the game will start their view point at which should be overlooking the map.  If more than one entity is created, one will be randomly chosen per player.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0"):
        Entity.__init__(self, "emp_info_map_overview", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname


        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles


        self.auto_properties.extend(["origin", "targetname", "parentname", "angles"])


class EmpInfoParams(Entity):
    """
    Auto-generated from empires.fgd, line 91.
    Empires Parameters.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", Skin=0, AutoResearch=0, NFRes=100, ImpRes=100, NFReinf=100, ImpReinf=100, eng_restrict_NF=0, eng_restrict_Imp=0, turretRestrict=0):
        Entity.__init__(self, "emp_info_params", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Map Theme : This is the setting/theme of the map and is only used to determine the camouflage that players wear.
        self.Skin = Skin
        # Automate Research? : Setting this to 'Yes' will automatically research the Research Tree, both teams will have the research tree fully researched.  You can also add or remove research items using the maps .cfg file for server side settings.
        self.AutoResearch = AutoResearch
        # Northern Faction Resources : The amount of resources the Northern Faction team starts with.
        self.NFRes = NFRes
        # Brenodi Empire Resources : The amount of resources the Brenodi Empire team starts with.
        self.ImpRes = ImpRes
        # Northern Faction Reinforcements : The amount of reinforcements the Northern Faction team starts with.
        self.NFReinf = NFReinf
        # Brenodi Empire Reinforcements : The amount of reinforcements the Brenodi Empire team starts with.
        self.ImpReinf = ImpReinf
        # Prevent NF Engineer Building : Select restrictions for the Northern Faction engineers from being able to build on this map.
        self.eng_restrict_NF = eng_restrict_NF
        # Prevent Brenodi Engineer Building : Select restrictions for the Brenodi Empire engineers from being able to build on this map.
        self.eng_restrict_Imp = eng_restrict_Imp
        # Prevent turret building : Does not affect the commander
        self.turretRestrict = turretRestrict

        self.auto_properties.extend(["origin", "targetname", "Skin", "AutoResearch", "NFRes", "ImpRes", "NFReinf", "ImpReinf", "eng_restrict_NF", "eng_restrict_Imp", "turretRestrict"])


class EmpInfoPlayerImp(Entity):
    """
    Auto-generated from empires.fgd, line 75.
    This entity indicates the position and facing direction at which a player on team Brenodi Empire will spawn during an Empires map. Any number of info_player_Imp entities may be placed in a map.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", pointNumber=0, spawnEnabled=0):
        Entity.__init__(self, "emp_info_player_Imp", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname


        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Enabled? : Is the spawn point enabled on start?
        self.spawnEnabled = spawnEnabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "pointNumber", "spawnEnabled"])


class EmpInfoPlayerNf(Entity):
    """
    Auto-generated from empires.fgd, line 58.
    This entity indicates the position and facing direction at which a player on team Northern Faction will spawn during an Empires map. Any number of info_player_NF entities may be placed in a map.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", pointNumber=0, spawnEnabled=0):
        Entity.__init__(self, "emp_info_player_NF", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname


        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Enabled? : Is the spawn point enabled on start?
        self.spawnEnabled = spawnEnabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "pointNumber", "spawnEnabled"])


class EmpMineRestrict(Entity):
    """
    Auto-generated from empires.fgd, line 1455.
    This brush will restrict the ability for grenadiers to drop mines.
    """
    def __init__(self, vmf_map, targetname="", parentname=""):
        Entity.__init__(self, "emp_mine_restrict", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname


        self.auto_properties.extend(["targetname", "parentname"])


class EmpNfAmmoCrate(Entity):
    """
    Auto-generated from empires.fgd, line 349.
    Northern Faction Ammo Crate which resupplies NF players with ammo when they 'use' the crate.  It never expires.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/NF/Props/nf_crateammo.mdl", fademindist=-1, fademaxdist=0, disableshadows=0, pointNumber=0, startDisabled=0):
        Entity.__init__(self, "emp_nf_ammo_crate", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Disabled? : If yes, then it will be invisible, not solid, and unusable until enabled by an input.
        self.startDisabled = startDisabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "fademindist", "fademaxdist", "disableshadows", "pointNumber", "startDisabled"])


class EmpNfCommander(Entity):
    """
    Auto-generated from empires.fgd, line 509.
    This entity is the Northern Faction commander's command tank.  Entering it allows him to drive the vehicle and to play the RTS aspect of the game (base building, issuing orders, etc) using his own unique interface.  The death of this unit ends the game. 
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0"):
        Entity.__init__(self, "emp_nf_commander", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles


        self.auto_properties.extend(["origin", "targetname", "angles"])


class EmpNfHealthCrate(Entity):
    """
    Auto-generated from empires.fgd, line 375.
    Northern Faction Health Crate which resupplies NF players with health when they 'use' the crate.  It never expires.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", model="models/NF/Props/nf_cratehealth.mdl", fademindist=-1, fademaxdist=0, disableshadows=0, pointNumber=0, startDisabled=0):
        Entity.__init__(self, "emp_nf_health_crate", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Number of the parent Capture Point : If this entity is to be enabled/disabled in association with the capture/loss of a capture point, input the associated capture point's number (defined in the capture point's properties)
        self.pointNumber = pointNumber
        # Start Disabled? : If yes, then it will be invisible, not solid, and unusable until enabled by an input.
        self.startDisabled = startDisabled

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "model", "fademindist", "fademaxdist", "disableshadows", "pointNumber", "startDisabled"])


class EmpResourcePoint(Entity):
    """
    Auto-generated from empires.fgd, line 450.
    This is a resource point that either team can build a refinery on.  Once a refinery is built, its resources will be extracted and given to the team's total resource pool.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", Enabled=1, MaxResources=-1, ResourcesSecond=1):
        Entity.__init__(self, "emp_resource_point", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Enabled? : If enabled, a refinery may be built on it.  If not enabled, then an entity within the map must enable it before a refinery can be built on it.
        self.Enabled = Enabled
        # Total Resources : The total number of resources that this resource point will give out.  '-1' is infinite.  A positive number is finite.
        self.MaxResources = MaxResources
        # Resources per Second : The amount of resources that will be extracted per second.
        self.ResourcesSecond = ResourcesSecond

        self.auto_properties.extend(["origin", "targetname", "angles", "Enabled", "MaxResources", "ResourcesSecond"])


class EmpResourcePointProp(Entity):
    """
    Auto-generated from empires.fgd, line 471.
    This is a resource point prop that is used for the visual representation of the resource point.  Its sole purpose is so that it will still allow a refinery to be built even though it is in contact with the refinery.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", angles="0 0 0", model="", skin=0, fademindist=-1, fademaxdist=0, disableshadows=0, Enabled=1):
        Entity.__init__(self, "emp_resource_point_prop", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Model : 
        self.model = model
        # Skin : Some models have multiple versions of their textures, called skins. Set this to a number other than 0 to use that skin instead of the default.
        self.skin = skin
        # Start Fade Dist : Distance at which the overlay starts to fade (<0 = use fademaxdist).
        self.fademindist = fademindist
        # End Fade Dist : Maximum distance at which the overlay is visible (0 = don't fade out).
        self.fademaxdist = fademaxdist
        # Disable Shadows : Used to disable dynamic shadows on this entity.
        self.disableshadows = disableshadows
        # Enabled? : If enabled, it will be visible.  It should be set to match its corresponding resource point.
        self.Enabled = Enabled

        self.auto_properties.extend(["origin", "targetname", "angles", "model", "skin", "fademindist", "fademaxdist", "disableshadows", "Enabled"])


class EmpTeamSoundPointentity(Entity):
    """
    Auto-generated from empires.fgd, line 1485.
    An entity that will play a sound only to a particular team
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", sound="", team=2, soundvolume=1, soundduration=0, soundradius=500, radiotext="", spawnflags=""):
        Entity.__init__(self, "emp_team_sound_pointentity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Sound : The specific name of the sound file or soundstring
        self.sound = sound
        # Team : The team who will recieve the sound
        self.team = team
        # Volume : Must be between 0 and 1,The volume the sound will play at.  if the sound uses the radio the volume will need to be significantly reduced
        self.soundvolume = soundvolume
        # Duration : The amount of time the sound will be playing for, a 0 duration means the sound will not be limited by duration
        self.soundduration = soundduration
        # Max Audible Distance : Maximum distance at which this sound is audible.
        self.soundradius = soundradius
        # Radio Text : Text displayed if this sound is played over the radio
        self.radiotext = radiotext
        # TODO: Replace this filler. : 
        self.spawnflags = spawnflags

        self.auto_properties.extend(["origin", "targetname", "sound", "team", "soundvolume", "soundduration", "soundradius", "radiotext", "spawnflags"])


class EmpTeamTextPointentity(Entity):
    """
    Auto-generated from empires.fgd, line 1505.
    An entity that will display a message to a particular team
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", text="", team=2):
        Entity.__init__(self, "emp_team_text_pointentity", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Text : Message displayed
        self.text = text
        # Team : The team who will recieve the message
        self.team = team

        self.auto_properties.extend(["origin", "targetname", "text", "team"])


class EmpTutorialBotSpawner(Entity):
    """
    Auto-generated from empires.fgd, line 1516.
    An entity that spawns tutorial bots for a particular team
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", team=2, class_=1, weaponPrimary="PRIMARY_NF_RIFLE", weaponSecondary="SIDEARM_NF_9MM", grenade="GRENADE_NF_EXPLOSIVE", equipment="EQUIP_NF_ARMOR", desiredBotCount=10, respawnTime=10, spawnPoint=""):
        Entity.__init__(self, "emp_tutorial_bot_spawner", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Team : The team the bot should get
        self.team = team
        # Class : The class the bots should use
        self.class_ = class_
        # Primary Weapon : The WeaponName of the weapon to use as primary. (see scripts/emp_weapons.txt)
        self.weaponPrimary = weaponPrimary
        # Secondary Weapon : The WeaponName of the weapon to use as secondary. (see scripts/emp_weapons.txt)
        self.weaponSecondary = weaponSecondary
        # Grenade : The WeaponName of the weapon to use as grenade. (see scripts/emp_weapons.txt)
        self.grenade = grenade
        # Equipment : The WeaponName of the weapon to use as equipment. (see scripts/emp_weapons.txt)
        self.equipment = equipment
        # Desired Bot Count : The amount of bots that should be spawned.
        self.desiredBotCount = desiredBotCount
        # Respawn Time : Amount of seconds bots should wait between respawning.
        self.respawnTime = respawnTime
        # Spawn Point : The name of the spawn point to use
        self.spawnPoint = spawnPoint

        self.auto_properties.extend(["origin", "targetname", "team", "class_", "weaponPrimary", "weaponSecondary", "grenade", "equipment", "desiredBotCount", "respawnTime", "spawnPoint"])


class EmpVehiclePreset(Entity):
    """
    Auto-generated from empires.fgd, line 977.
    
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", teamNumber=2, spawnPoint=0, cost=0, chassisType=0, engineType=0, armorType=0, armorFront=0, armorRear=0, armorLeft=0, armorRight=0, weaponType1=-1, weaponMode1=0, weaponGroup1=0, weaponType2=-1, weaponMode2=0, weaponGroup2=0, weaponType3=-1, weaponMode3=0, weaponGroup3=0, weaponType4=-1, weaponMode4=0, weaponGroup4=0, weaponType5=-1, weaponMode5=0, weaponGroup5=0, weaponType6=-1, weaponMode6=0, weaponType7=-1, weaponMode7=0, weaponGroup7=0, weaponType8=-1, weaponMode8=0, weaponGroup8=0):
        Entity.__init__(self, "emp_vehicle_preset", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Faction : Which faction will own the tank.
        self.teamNumber = teamNumber
        # Spawn Point : Whether or not this vehicle will act as a mobile spawn point. Any APC that spawns after APD has been researched will act as a spawn point, regardless of this setting.
        self.spawnPoint = spawnPoint
        # Cost : The cost of the vehicle (will not build if the team cannot afford).
        self.cost = cost
        # Chassis : Chassis Type.
        self.chassisType = chassisType
        # Engine : Engine Type (Jeep, Apc, LT, Med, Heavy, Artillery).
        self.engineType = engineType
        # Armor : Armor Type
        self.armorType = armorType
        # Front Armor Plates : How many plates on the tank's Front?
        self.armorFront = armorFront
        # Rear Armor Plates : How many plates on the tank's Rear?
        self.armorRear = armorRear
        # Left Armor Plates : How many plates on the tank's Left?
        self.armorLeft = armorLeft
        # Right Armor Plates : How many plates on the tank's Right?
        self.armorRight = armorRight
        # Weapon 1: Type : ID for the weapon type.
        self.weaponType1 = weaponType1
        # Weapon 1: Mode : The key binding for this weapon.
        self.weaponMode1 = weaponMode1
        # Weapon 1: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup1 = weaponGroup1
        # Weapon 2: Type : ID for the weapon type.
        self.weaponType2 = weaponType2
        # Weapon 2: Mode : The key binding for this weapon.
        self.weaponMode2 = weaponMode2
        # Weapon 2: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup2 = weaponGroup2
        # Weapon 3: Type : ID for the weapon type.
        self.weaponType3 = weaponType3
        # Weapon 3: Mode : The key binding for this weapon.
        self.weaponMode3 = weaponMode3
        # Weapon 3: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup3 = weaponGroup3
        # Weapon 4: Type : ID for the weapon type.
        self.weaponType4 = weaponType4
        # Weapon 4: Mode : The key binding for this weapon.
        self.weaponMode4 = weaponMode4
        # Weapon 4: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup4 = weaponGroup4
        # Weapon 5: Type : ID for the weapon type.
        self.weaponType5 = weaponType5
        # Weapon 5: Mode : The key binding for this weapon.
        self.weaponMode5 = weaponMode5
        # Weapon 5: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup5 = weaponGroup5
        # Weapon 6: Type : ID for the weapon type.
        self.weaponType6 = weaponType6
        # Weapon 6: Mode : The key binding for this weapon.
        self.weaponMode6 = weaponMode6
        # Weapon 7: Type : ID for the weapon type.
        self.weaponType7 = weaponType7
        # Weapon 7: Mode : The key binding for this weapon.
        self.weaponMode7 = weaponMode7
        # Weapon 7: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup7 = weaponGroup7
        # Weapon 8: Type : ID for the weapon type.
        self.weaponType8 = weaponType8
        # Weapon 8: Mode : The key binding for this weapon.
        self.weaponMode8 = weaponMode8
        # Weapon 8: Groups : The weapon groups will this weapon will be associated with, (add 1,2,4,8,16,32)
        self.weaponGroup8 = weaponGroup8

        self.auto_properties.extend(["origin", "targetname", "teamNumber", "spawnPoint", "cost", "chassisType", "engineType", "armorType", "armorFront", "armorRear", "armorLeft", "armorRight", "weaponType1", "weaponMode1", "weaponGroup1", "weaponType2", "weaponMode2", "weaponGroup2", "weaponType3", "weaponMode3", "weaponGroup3", "weaponType4", "weaponMode4", "weaponGroup4", "weaponType5", "weaponMode5", "weaponGroup5", "weaponType6", "weaponMode6", "weaponType7", "weaponMode7", "weaponGroup7", "weaponType8", "weaponMode8", "weaponGroup8"])


class EmpVehicleSpawnBrush(Entity):
    """
    Auto-generated from empires.fgd, line 1569.
    This brush allows people to build a vehicle via the vehicle customization menu by pressing V.
    """
    def __init__(self, vmf_map, targetname="", parentname="", Enabled=1, BEEnabled=1, NFEnabled=1):
        Entity.__init__(self, "emp_vehicle_spawn_brush", vmf_map)

        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Enable this brush : Warning: BE/NFEnabled still needed to enable this brush
        self.Enabled = Enabled
        # Enable BE infantry to build vehicles here : Warning: Enabled is first checked for, don't forget to enable it
        self.BEEnabled = BEEnabled
        # Enable NF infantry to build vehicles here : Warning: Enabled is first checked for, don't forget to enable it
        self.NFEnabled = NFEnabled

        self.auto_properties.extend(["targetname", "parentname", "Enabled", "BEEnabled", "NFEnabled"])


class EmpVehicleSpawner(Entity):
    """
    Auto-generated from empires.fgd, line 1432.
    
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", parentname="", angles="0 0 0", enabled=1, autorespawn=0, CostsResources=1):
        Entity.__init__(self, "emp_vehicle_spawner", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Parent : The name of this entity's parent in the movement hierarchy. Entities with parents move with their parent.
        self.parentname = parentname

        # Pitch Yaw Roll (Y Z X) : This entity's orientation in the world. Pitch is rotation around the Y axis, 
        self.angles = angles

        # Start Enabled : Should this entity start enabled?
        self.enabled = enabled
        # Automatically Respawn? : Monitor the last spawned vehicle, and respawn if necessary. (Only monitors one vehicle at a time)
        self.autorespawn = autorespawn
        # Costs resources? : If set, deducts the appropiate resource count from the teams balance
        self.CostsResources = CostsResources

        self.auto_properties.extend(["origin", "targetname", "parentname", "angles", "enabled", "autorespawn", "CostsResources"])


class FilterActivatorTeam(Entity):
    """
    Auto-generated from empires.fgd, line 1459.
    A filter that filters by the team of the activator.
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", Negated="Allow entities that match criteria", filterteam=2):
        Entity.__init__(self, "filter_activator_team", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Filter mode : If set to Allow, only entities who match the criteria will pass the filter. 
        self.Negated = Negated

        # Filter Team Number : The team number to filter by.  If the filter mode is Allow, only entities whose 
        self.filterteam = filterteam

        self.auto_properties.extend(["origin", "targetname", "Negated", "filterteam"])


class InfoEmphint(Entity):
    """
    Auto-generated from empires.fgd, line 1552.
    Empires hint, shown as a box in the HUD
    """
    def __init__(self, vmf_map, origin="0 0 0", targetname="", forceDisplay=0, title="", text=""):
        Entity.__init__(self, "info_emphint", vmf_map)

        # Origin : This entity's location in 3D space.
        self.origin = origin
        # Name : The name that other entities refer to this entity by.
        self.targetname = targetname

        # Force hint : Hint will be shown regardlessly of emp_cl_hints_enabled CVar
        self.forceDisplay = forceDisplay
        # Hint title : Must be kept under 32 chars
        self.title = title
        # Hint text : Limited by string table
        self.text = text

        self.auto_properties.extend(["origin", "targetname", "forceDisplay", "title", "text"])


